### ISSUE TITLE
F11 (hide UI) does not hide the compass

### ISSUE THREAD

**Issue by krisis-nl** [appuns/DSPCompass#2]
Don't know whether this classifies as a feature request, but I think it could be considered a bug: when you press F11 to hide the UI, the compass remains. And when you press F11 again Icarus disappears, but the compass remains. Now I personally don't mind the compass showing when Icarus still shows, but the second situation is quite bothersome when you want to take a nice screenshot or recording and the compass is still there. But effectively, the compass should disappear in both situations. It's part of the UI however way you put it. Thanks for reading, hope you find the time to add this. I like the mod very much, but now I have to restart the game with the mod disabled whenever I feel like recording.

**Comment by appuns** [comment]
Updated. check plz.
